name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:lts-alpine
      ports:
        - 3000:3000
        - 5000:5000
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: node:lts-alpine
      ports:
        - 3000:3000
        - 5000:5000
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: ./jenkins/scripts/test.sh

  deliver-for-development:
    needs: test
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    container:
      image: node:lts-alpine
      ports:
        - 3000:3000
        - 5000:5000
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - name: Deliver for development
        run: ./jenkins/scripts/deliver-for-development.sh
      - name: Manual confirmation
        run: echo "Manual confirmation required, finished using the website? (Proceed to continue)" && exit 0
      - name: Kill process
        run: ./jenkins/scripts/kill.sh

  deploy-for-production:
    needs: test
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    container:
      image: node:lts-alpine
      ports:
        - 3000:3000
        - 5000:5000
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - name: Deploy for production
        run: ./jenkins/scripts/deploy-for-production.sh
      - name: Manual confirmation
        run: echo "Manual confirmation required, finished using the website? (Proceed to continue)" && exit 0
      - name: Kill process
        run: ./jenkins/scripts/kill.sh
